### PR TITLE
Updated install commands

### PR DESCRIPTION
**Pull request by kymellis**
While covering support this week I had a few questions about migrations from other platforms - and I noticed that there are people out there who are savvy enough to be ideal Ghost(Pro) customers trying to make use of the info on our migrations page here: https://docs.ghost.org/api/migration/

I had one person who has already migrated their content from Medium > WordPress, who was trying to figure out how to use the Ghost WP plugin workaround and getting stuck (understandably). 

I was curious to see if I even knew how to do it, and immediately got tripped up when trying to figure out how to install v1 locally as I couldn't find the command from this page.

This PR is a suggestion to improve the commands listed to be clearer about how to specify a version. Still not sure if this is the best way to do it because using square brackets can be confusing 🤔The only other way I can think of is to actually use `v1` as an example, but this might be encouraging the wrong thing. 

`ghost install --v1`
`ghost install --v1 local`

---
**Related question:** If we're not going to have a clearer migration path in the near future, then would it be worth me doing an FAQ for the current workaround (using the plugin) to send to people who are getting stuck? 

It would make the support process for those tickets smoother - but I'm not so sure if it would actually result in more migrations to Ghost since most people will just put their hands up and say they'll come back later.

### CODE REVIEW

**Comment by ErisDS** [comment]
We have https://ghost.org/update/ which I remember there were different versions of for different versions, but I can't remember how we access them @JohnONolan ?

There was a plan to roll this page out, but I think it got lost.

I do think an FAQ would be handy. We also need one for how to switch your theme to the v2 API, which we haven't done and is causing confusion.

**Comment by JohnONolan** [comment]
https://ghost.org/update/?v=0.12.1

**Comment by ErisDS** [comment]
FWIW I only figured ^ out by go reading the code cos I smelled something was off. 

`ghost --help` and `ghost install --help` isn't that much clearer either.

**Comment by ErisDS** [comment]
> https://ghost.org/update/?v=0.12.1

@JohnONolan 👍 👍  should we update the default notifications to include the version string on the end?

**Comment by JohnONolan** [comment]
Yes ideally

**Comment by ErisDS** [comment]
ok cool - we're about to start working on this area next week so I'll add it in.

**Comment by kymellis** [comment]
Happy for someone else to write some better suggested changes for the CLI docs and close this PR. Just wanted to open up a thread. I made a suggestion based on the one example I was stuck with - but the docs need to be correct for all use cases so could definitely use some help to review :)  

What I was trying to do specifically was install V1 (latest version) locally. I couldn't figure out how to construct this command based on the current docs for a local install. `ghost install v1 local` didn't work for me with the following error: 

`System checks failed with message: 'Operating system is not Linux'
Some features of Ghost-CLI may not work without additional configuration.
For local installs we recommend using `ghost install local` instead.`

I was using this to help someone figure out how to use the old WordPress migrator. Right now you need to do a work around of installing v1 locally, importing, upgrading, exporting and importing again. 

> This is the process that I am unsure if we should document as a temporary FAQ, until we have a better migration path in place. We allude to this on the migrations page but it doesn't go into detail about how to actually do it. If we won't have a migration tool for a little while longer it might be worth having something we can point people towards because we do get pro customers and trial users asking about it.

https://ghost.org/update/?v=0.12.1 <-- this is a great guide for upgrades. It's not published on docs, but I think this was done on purpose, because we link people to these pages from within Ghost.

**Comment by ErisDS** [comment]
@JohnONolan derp. It's done. I was testing it without telling it what version I was on. Different problem to solve.

@kymellis I will take a stab at updating the docs

**Comment by kymellis** [comment]
@ErisDS OK sounds good, speaking to Sarah about support tickets regarding migrations and will figure out if we need a new FAQ for that.

**Comment by ErisDS** [comment]
Closing in favour of #51 🙂

**Pull request closed without merging**
